// src/app/features/field-library-sidebar/field-library-sidebar.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CdkDragDrop, DragDropModule, moveItemInArray } from '@angular/cdk/drag-drop';
import { TemplateService, FIELD_TYPES } from '../../services/template.service';
import { Field, Library, CustomField } from '../../types';
import { IconComponent } from '../icon/icon.component';

@Component({
  selector: 'app-field-library-sidebar',
  standalone: true,
  imports: [CommonModule, DragDropModule, IconComponent],
  template: `
    <div 
      class="border-r border-gray-200 bg-white flex flex-col transition-all duration-300 fixed left-0 z-30"
      [style.width]="service.sidebarCollapsed() ? '48px' : '288px'"
      style="top: 57px; height: calc(100vh - 57px); max-height: calc(100vh - 57px);"
    >
      <ng-container *ngIf="!service.sidebarCollapsed(); else collapsedView">
        <!-- Field List Section -->
        <div 
          class="flex flex-col border-b border-gray-300"
          [style.height.%]="fieldListHeight"
        >
          <!-- Field List Header -->
          <div class="px-4 py-3 border-b border-gray-200 flex items-center justify-between bg-gray-50">
            <div class="flex items-center gap-2">
              <app-icon key="list" className="w-4 h-4 text-gray-600"></app-icon>
              <h3 class="text-sm font-medium text-gray-900">Fields ({{ service.fields().length }})</h3>
            </div>
            <button
              (click)="service.sidebarCollapsed.set(true)"
              class="text-gray-400 hover:text-gray-600 transition-colors cursor-pointer"
              title="Collapse sidebar"
            >
              <span class="text-xs">◀</span>
            </button>
          </div>

          <!-- Field List - Drag & Drop Scrollable -->
          <div 
            class="flex-1 overflow-y-auto custom-scrollbar"
            cdkDropList
            (cdkDropListDropped)="onFieldDrop($event)"
          >
            <div *ngIf="service.fields().length === 0" class="p-4 text-center text-sm text-gray-500">
              No fields yet
            </div>
            <div 
              *ngFor="let field of service.fields(); let idx = index"
              cdkDrag
              (click)="service.selectedField.set(field.id)"
              class="w-full flex items-center gap-2 px-3 py-2 hover:bg-gray-50 transition-colors border-l-3 group cursor-pointer"
              [class.bg-gray-100]="service.selectedField() === field.id"
              [style.borderLeftColor]="service.selectedField() === field.id ? service.COLORS.primary : 'transparent'"
              style="border-left-width: 3px; border-left-style: solid;"
            >
              <span class="text-gray-600 flex-shrink-0">
                <app-icon [key]="getFieldIconKey(field)" className="w-5 h-5"></app-icon>
              </span>
              <div class="flex-1 text-left min-w-0">
                <div class="text-sm text-gray-900 truncate">{{ field.name }}</div>
              </div>
              <div 
                class="w-2 h-2 rounded-full flex-shrink-0"
                [style.backgroundColor]="service.selectedField() === field.id ? service.COLORS.primary : '#94A3B8'"
              ></div>
              <div class="flex-shrink-0 text-gray-300 group-hover:text-gray-500 transition-colors cursor-grab" cdkDragHandle>
                <app-icon key="list" className="w-3 h-3"></app-icon>
              </div>
            </div>
          </div>
        </div>

        <!-- Draggable Divider -->
        <div
          (mousedown)="onResizeStart($event)"
          class="h-2 bg-gray-100 hover:bg-gray-200 cursor-ns-resize flex items-center justify-center border-y border-gray-200 transition-colors"
          [style.backgroundColor]="isResizing() ? '#d1d5db' : ''"
          style="user-select: none;"
        >
          <div class="w-8 h-1 bg-gray-300 rounded"></div>
        </div>

        <!-- Add Fields Section -->
        <div 
          class="flex flex-col"
          [style.height.%]="100 - fieldListHeight"
        >
          <!-- Add Fields Header -->
          <div class="px-4 py-3 border-b border-gray-200 bg-gray-50">
            <h3 class="text-sm font-semibold text-gray-700 uppercase tracking-wide">
              Libraries & Fields
            </h3>
          </div>

          <!-- Scrollable Content -->
          <div class="flex-1 overflow-y-auto custom-scrollbar">
            <!-- Built-in Field Types -->
            <div class="border-b border-gray-200">
              <button
                (click)="expandedBuiltIn.set(!expandedBuiltIn())"
                class="w-full flex items-center justify-between p-3 hover:bg-gray-50 transition-colors text-left cursor-pointer"
              >
                <span class="text-sm font-medium text-gray-900">Built-in Fields</span>
                <span class="text-xs text-gray-500 transition-transform" [class.rotate-90]="!expandedBuiltIn()">▼</span>
              </button>
              
              <div *ngIf="expandedBuiltIn()" class="pb-2 animate-fade-in">
                <button
                  *ngFor="let item of visibleFieldTypesList"
                  (click)="service.addField(item.key, service.fields().length)"
                  class="w-full flex items-center gap-2 px-4 py-2 hover:bg-gray-50 transition-colors group text-left cursor-pointer border-l-3 border-transparent"
                  [style.hoverBorderLeftColor]="service.COLORS.primary"
                  [style.hoverBackgroundColor]="service.COLORS.primaryLight"
                >
                  <span class="text-gray-600">
                    <app-icon [key]="item.key" className="w-5 h-5"></app-icon>
                  </span>
                  <span class="text-sm text-gray-900 flex-1">{{ item.value.label }}</span>
                  <span class="text-sm text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity font-bold">＋</span>
                </button>
              </div>
            </div>

            <!-- Library Fields -->
            <div *ngFor="let library of service.libraries()" class="border-b border-gray-200">
              <button
                (click)="toggleLibrary(library.id)"
                class="w-full flex items-center justify-between p-3 hover:bg-gray-50 transition-colors text-left cursor-pointer"
              >
                <span class="text-sm font-medium text-gray-900">{{ library.name }}</span>
                <span class="text-xs text-gray-500 transition-transform" [class.rotate-90]="!expandedLibraries().has(library.id)">▼</span>
              </button>
              
              <div *ngIf="expandedLibraries().has(library.id)" class="pb-2 animate-fade-in">
                <div *ngIf="getFieldsForLibrary(library.id).length === 0" class="px-4 py-2 text-xs text-gray-500 italic">
                  No fields in this library
                </div>
                <button
                  *ngFor="let field of getFieldsForLibrary(library.id)"
                  (click)="service.addCustomFieldToTemplate(field, service.fields().length)"
                  class="w-full flex items-center gap-2 px-4 py-2 hover:bg-gray-50 transition-colors group text-left cursor-pointer border-l-3 border-transparent"
                >
                  <span class="text-gray-600">
                    <app-icon [key]="field.baseType" className="w-5 h-5"></app-icon>
                  </span>
                  <div class="flex-1 text-left min-w-0">
                    <div class="text-sm text-gray-900">{{ field.name }}</div>
                    <div *ngIf="field.description" class="text-xs text-gray-500 truncate">{{ field.description }}</div>
                  </div>
                  <span class="text-sm text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity font-bold flex-shrink-0">＋</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </ng-container>

      <!-- Collapsed View -->
      <ng-template #collapsedView>
        <div class="flex flex-col h-full">
          <!-- Expand Button -->
          <div class="p-3 border-b border-gray-200 flex justify-center">
            <button
              (click)="service.sidebarCollapsed.set(false)"
              class="text-gray-400 hover:text-gray-600 transition-colors cursor-pointer"
              title="Expand sidebar"
            >
              <span class="text-xs">▶</span>
            </button>
          </div>

          <!-- Collapsed Icons -->
          <div class="flex-1 overflow-y-auto custom-scrollbar py-2">
            <!-- Field count indicator -->
            <div class="flex justify-center py-2 border-b border-gray-200">
              <div class="relative">
                <app-icon key="list" className="w-5 h-5 text-gray-600"></app-icon>
                <div 
                  *ngIf="service.fields().length > 0" 
                  class="absolute -top-1 -right-1 w-3 h-3 rounded-full text-xs flex items-center justify-center font-bold"
                  [style.backgroundColor]="service.COLORS.primary"
                  style="font-size: 8px; color: white;"
                >
                  {{ service.fields().length }}
                </div>
              </div>
            </div>

            <!-- Built-in indicator -->
            <div class="flex justify-center py-2 border-b border-gray-200">
              <span class="text-lg font-bold text-gray-500">＋</span>
            </div>
            
            <!-- Library indicators -->
            <div 
              *ngFor="let library of service.libraries(); let last = last" 
              class="flex justify-center py-2"
              [class.border-b]="!last"
              [class.border-gray-200]="!last"
            >
              <app-icon key="library" className="w-5 h-5 text-gray-600"></app-icon>
            </div>
          </div>
        </div>
      </ng-template>
    </div>
  `,
  styles: [`
    .custom-scrollbar::-webkit-scrollbar {
      width: 6px;
    }
    .custom-scrollbar::-webkit-scrollbar-track {
      background: #f9fafb;
      border-radius: 3px;
    }
    .custom-scrollbar::-webkit-scrollbar-thumb {
      background: #d1d5db;
      border-radius: 3px;
    }
    .custom-scrollbar::-webkit-scrollbar-thumb:hover {
      background: #9ca3af;
    }
    .border-l-3 {
      border-left-width: 3px;
    }
    /* Simple hover class styling */
    button.border-l-3:hover {
      border-left-color: #2D6F5F !important;
      background-color: #E8F3F0 !important;
    }
  `]
})
export class FieldLibrarySidebarComponent {
  readonly service = inject(TemplateService);

  fieldListHeight = 33.33; // percentage
  readonly isResizing = signal(false);
  readonly expandedBuiltIn = signal(true);
  readonly expandedLibraries = signal<Set<number>>(new Set());

  get visibleFieldTypesList() {
    const visible = this.service.preferences().visibleFieldTypes;
    return Object.entries(FIELD_TYPES)
      .filter(([key]) => visible[key] !== false)
      .map(([key, value]) => ({ key, value }));
  }

  getFieldIconKey(field: Field): string {
    if (field.customFieldId) {
      const customField = this.service.customFields().find(cf => cf.id === field.customFieldId);
      if (customField) {
        return customField.baseType;
      }
    }
    return field.type;
  }

  getFieldsForLibrary(libraryId: number): CustomField[] {
    return this.service.customFields().filter(cf => cf.libraryId === libraryId);
  }

  toggleLibrary(libraryId: number) {
    this.expandedLibraries.update(prev => {
      const next = new Set(prev);
      if (next.has(libraryId)) {
        next.delete(libraryId);
      } else {
        next.add(libraryId);
      }
      return next;
    });
  }

  onFieldDrop(event: CdkDragDrop<Field[]>) {
    this.service.moveField(event.previousIndex, event.currentIndex);
  }

  onResizeStart(e: MouseEvent) {
    e.preventDefault();
    e.stopPropagation();
    this.isResizing.set(true);

    const onMouseMove = (moveEvent: MouseEvent) => {
      const container = document.querySelector('.border-r');
      if (!container) return;
      
      const containerRect = container.getBoundingClientRect();
      const newHeight = ((moveEvent.clientY - containerRect.top) / containerRect.height) * 100;
      
      // Constrain between 10% and 75%
      this.fieldListHeight = Math.min(Math.max(newHeight, 10), 75);
    };

    const onMouseUp = () => {
      this.isResizing.set(false);
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };

    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
  }
}

<div 
  class="border-r border-gray-200 bg-white flex flex-col transition-all duration-300 fixed left-0 z-30"
  [style.width]="service.sidebarCollapsed() ? '48px' : '288px'"
  style="top: 57px; height: calc(100vh - 57px); max-height: calc(100vh - 57px);"
>
  <ng-container *ngIf="!service.sidebarCollapsed(); else collapsedView">
    <!-- Field List Section -->
    <div 
      class="flex flex-col border-b border-gray-300"
      [style.height.%]="fieldListHeight"
    >
      <!-- Field List Header -->
      <div class="px-4 py-3 border-b border-gray-200 flex items-center justify-between bg-gray-50">
        <div class="flex items-center gap-2">
          <app-icon key="list" className="w-4 h-4 text-gray-600"></app-icon>
          <h3 class="text-sm font-medium text-gray-900">Fields ({{ service.fields().length }})</h3>
        </div>
        <button
          (click)="service.sidebarCollapsed.set(true)"
          class="text-gray-400 hover:text-gray-600 transition-colors cursor-pointer"
          title="Collapse sidebar"
        >
          <span class="text-xs">◀</span>
        </button>
      </div>

      <!-- Field List - Drag & Drop Scrollable -->
      <div 
        class="flex-1 overflow-y-auto custom-scrollbar"
        cdkDropList
        (cdkDropListDropped)="onFieldDrop($event)"
      >
        <div *ngIf="service.fields().length === 0" class="p-4 text-center text-sm text-gray-500">
          No fields yet
        </div>
        <div 
          *ngFor="let field of service.fields(); let idx = index"
          cdkDrag
          (click)="service.selectedField.set(field.id)"
          class="w-full flex items-center gap-2 px-3 py-2 hover:bg-gray-50 transition-colors border-l-3 group cursor-pointer"
          [class.bg-gray-100]="service.selectedField() === field.id"
          [style.borderLeftColor]="service.selectedField() === field.id ? service.COLORS.primary : 'transparent'"
          style="border-left-width: 3px; border-left-style: solid;"
        >
          <span class="text-gray-600 flex-shrink-0">
            <app-icon [key]="getFieldIconKey(field)" className="w-5 h-5"></app-icon>
          </span>
          <div class="flex-1 text-left min-w-0">
            <div class="text-sm text-gray-900 truncate">{{ field.name }}</div>
          </div>
          <div 
            class="w-2 h-2 rounded-full flex-shrink-0"
            [style.backgroundColor]="service.selectedField() === field.id ? service.COLORS.primary : '#94A3B8'"
          ></div>
          <div class="flex-shrink-0 text-gray-300 group-hover:text-gray-500 transition-colors cursor-grab" cdkDragHandle>
            <app-icon key="list" className="w-3 h-3"></app-icon>
          </div>
        </div>
      </div>
    </div>

    <!-- Draggable Divider -->
    <div
      (mousedown)="onResizeStart($event)"
      class="h-2 bg-gray-100 hover:bg-gray-200 cursor-ns-resize flex items-center justify-center border-y border-gray-200 transition-colors"
      [style.backgroundColor]="isResizing() ? '#d1d5db' : ''"
      style="user-select: none;"
    >
      <div class="w-8 h-1 bg-gray-300 rounded"></div>
    </div>

    <!-- Add Fields Section -->
    <div 
      class="flex flex-col"
      [style.height.%]="100 - fieldListHeight"
    >
      <!-- Add Fields Header -->
      <div class="px-4 py-3 border-b border-gray-200 bg-gray-50">
        <h3 class="text-sm font-semibold text-gray-700 uppercase tracking-wide">
          Libraries & Fields
        </h3>
      </div>

      <!-- Scrollable Content -->
      <div class="flex-1 overflow-y-auto custom-scrollbar">
        <!-- Built-in Field Types -->
        <div class="border-b border-gray-200">
          <button
            (click)="expandedBuiltIn.set(!expandedBuiltIn())"
            class="w-full flex items-center justify-between p-3 hover:bg-gray-50 transition-colors text-left cursor-pointer"
          >
            <span class="text-sm font-medium text-gray-900">Built-in Fields</span>
            <span class="text-xs text-gray-500 transition-transform" [class.rotate-90]="!expandedBuiltIn()">▼</span>
          </button>
          
          <div *ngIf="expandedBuiltIn()" class="pb-2 animate-fade-in">
            <button
              *ngFor="let item of visibleFieldTypesList"
              (click)="service.addField(item.key, service.fields().length)"
              class="w-full flex items-center gap-2 px-4 py-2 hover:bg-gray-50 transition-colors group text-left cursor-pointer border-l-3 border-transparent"
              [style.hoverBorderLeftColor]="service.COLORS.primary"
              [style.hoverBackgroundColor]="service.COLORS.primaryLight"
            >
              <span class="text-gray-600">
                <app-icon [key]="item.key" className="w-5 h-5"></app-icon>
              </span>
              <span class="text-sm text-gray-900 flex-1">{{ item.value.label }}</span>
              <span class="text-sm text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity font-bold">＋</span>
            </button>
          </div>
        </div>

        <!-- Library Fields -->
        <div *ngFor="let library of service.libraries()" class="border-b border-gray-200">
          <button
            (click)="toggleLibrary(library.id)"
            class="w-full flex items-center justify-between p-3 hover:bg-gray-50 transition-colors text-left cursor-pointer"
          >
            <span class="text-sm font-medium text-gray-900">{{ library.name }}</span>
            <span class="text-xs text-gray-500 transition-transform" [class.rotate-90]="!expandedLibraries().has(library.id)">▼</span>
          </button>
          
          <div *ngIf="expandedLibraries().has(library.id)" class="pb-2 animate-fade-in">
            <div *ngIf="getFieldsForLibrary(library.id).length === 0" class="px-4 py-2 text-xs text-gray-500 italic">
              No fields in this library
            </div>
            <button
              *ngFor="let field of getFieldsForLibrary(library.id)"
              (click)="service.addCustomFieldToTemplate(field, service.fields().length)"
              class="w-full flex items-center gap-2 px-4 py-2 hover:bg-gray-50 transition-colors group text-left cursor-pointer border-l-3 border-transparent"
            >
              <span class="text-gray-600">
                <app-icon [key]="field.baseType" className="w-5 h-5"></app-icon>
              </span>
              <div class="flex-1 text-left min-w-0">
                <div class="text-sm text-gray-900">{{ field.name }}</div>
                <div *ngIf="field.description" class="text-xs text-gray-500 truncate">{{ field.description }}</div>
              </div>
              <span class="text-sm text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity font-bold flex-shrink-0">＋</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </ng-container>

  <!-- Collapsed View -->
  <ng-template #collapsedView>
    <div class="flex flex-col h-full">
      <!-- Expand Button -->
      <div class="p-3 border-b border-gray-200 flex justify-center">
        <button
          (click)="service.sidebarCollapsed.set(false)"
          class="text-gray-400 hover:text-gray-600 transition-colors cursor-pointer"
          title="Expand sidebar"
        >
          <span class="text-xs">▶</span>
        </button>
      </div>

      <!-- Collapsed Icons -->
      <div class="flex-1 overflow-y-auto custom-scrollbar py-2">
        <!-- Field count indicator -->
        <div class="flex justify-center py-2 border-b border-gray-200">
          <div class="relative">
            <app-icon key="list" className="w-5 h-5 text-gray-600"></app-icon>
            <div 
              *ngIf="service.fields().length > 0" 
              class="absolute -top-1 -right-1 w-3 h-3 rounded-full text-xs flex items-center justify-center font-bold"
              [style.backgroundColor]="service.COLORS.primary"
              style="font-size: 8px; color: white;"
            >
              {{ service.fields().length }}
            </div>
          </div>
        </div>

        <!-- Built-in indicator -->
        <div class="flex justify-center py-2 border-b border-gray-200">
          <span class="text-lg font-bold text-gray-500">＋</span>
        </div>
        
        <!-- Library indicators -->
        <div 
          *ngFor="let library of service.libraries(); let last = last" 
          class="flex justify-center py-2"
          [class.border-b]="!last"
          [class.border-gray-200]="!last"
        >
          <app-icon key="library" className="w-5 h-5 text-gray-600"></app-icon>
        </div>
      </div>
    </div>
  </ng-template>
</div>

// react-src-backup/src/app/components/FieldLibrarySidebar.tsx
import { ChevronDown, ChevronRight, ChevronLeft, GripHorizontal, Plus } from 'lucide-react';
import { useState, useRef, useEffect } from 'react';
import { DraggableFieldListItem } from './DraggableFieldListItem';

interface Library {
  id: number;
  name: string;
  description: string;
  icon: string;
}

interface CustomField {
  id: number;
  name: string;
  icon: string;
  baseType: string;
  libraryId: number;
  description: string;
  placeholder: string;
  validationRules: any[];
}

interface Field {
  id: number;
  type: string;
  name: string;
  status: string;
  options: string[];
  defaultValue: string;
  allowMultiple: boolean;
  helpText?: string;
  customFieldId?: number;
  libraryId?: number;
}

interface FieldType {
  icon: JSX.Element;
  label: string;
  preview: string;
}

interface FieldLibrarySidebarProps {
  libraries: Library[];
  customFields: CustomField[];
  fields: Field[];
  fieldTypes: Record<string, FieldType>;
  visibleFieldTypes: Record<string, boolean>;
  onAddField: (type: string) => void;
  onAddCustomField: (customField: CustomField) => void;
  onFieldClick?: (fieldId: number) => void;
  selectedField: number | null;
  onCollapsedChange?: (isCollapsed: boolean) => void;
  moveField: (dragIndex: number, hoverIndex: number) => void;
  COLORS: {
    primary: string;
    primaryHover: string;
    primaryLight: string;
    border: string;
  };
}

export function FieldLibrarySidebar({
  libraries,
  customFields,
  fields,
  fieldTypes,
  visibleFieldTypes,
  onAddField,
  onAddCustomField,
  onFieldClick,
  selectedField,
  onCollapsedChange,
  moveField,
  COLORS
}: FieldLibrarySidebarProps) {
  const [expandedLibraries, setExpandedLibraries] = useState<Set<number>>(new Set());
  const [expandedBuiltIn, setExpandedBuiltIn] = useState(true);
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [fieldListHeight, setFieldListHeight] = useState(33.33); // percentage
  const [isDragging, setIsDragging] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  const toggleLibrary = (libraryId: number) => {
    setExpandedLibraries(prev => {
      const next = new Set(prev);
      if (next.has(libraryId)) {
        next.delete(libraryId);
      } else {
        next.add(libraryId);
      }
      return next;
    });
  };

  const getVisibleFieldTypes = () => {
    return Object.entries(fieldTypes).filter(([key]) => visibleFieldTypes[key] !== false);
  };

  const getFieldsForLibrary = (libraryId: number) => {
    return customFields.filter(cf => cf.libraryId === libraryId);
  };

  const handleMouseDown = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  };

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (!isDragging || !containerRef.current) return;

      const containerRect = containerRef.current.getBoundingClientRect();
      const newHeight = ((e.clientY - containerRect.top) / containerRect.height) * 100;
      
      // Constrain between 10% and 70%
      setFieldListHeight(Math.min(Math.max(newHeight, 10), 70));
    };

    const handleMouseUp = () => {
      setIsDragging(false);
    };

    if (isDragging) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isDragging]);

  const getFieldIcon = (field: Field) => {
    if (field.customFieldId) {
      const customField = customFields.find(cf => cf.id === field.customFieldId);
      if (customField) {
        return fieldTypes[customField.baseType]?.icon || fieldTypes[field.type]?.icon;
      }
    }
    return fieldTypes[field.type]?.icon;
  };

  return (
    <div 
      ref={containerRef}
      className="border-r border-gray-200 bg-white flex flex-col transition-all duration-300 fixed left-0 z-30"
      style={{ 
        width: isCollapsed ? '48px' : '288px',
        top: '57px',
        height: 'calc(100vh - 57px)',
        maxHeight: 'calc(100vh - 57px)'
      }}
    >
      {!isCollapsed ? (
        <>
          {/* Field List Section */}
          <div 
            className="flex flex-col border-b border-gray-300"
            style={{ height: `${fieldListHeight}%` }}
          >
            {/* Field List Header */}
            <div className="px-4 py-3 border-b border-gray-200 flex items-center justify-between bg-gray-50">
              <div className="flex items-center gap-2">
                <svg className="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                </svg>
                <h3 className="text-sm font-medium text-gray-900">Fields ({fields.length})</h3>
              </div>
              <button
                onClick={() => {
                  setIsCollapsed(true);
                  onCollapsedChange?.(true);
                }}
                className="text-gray-400 hover:text-gray-600 transition-colors"
                title="Collapse sidebar"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
            </div>

            {/* Field List - Scrollable */}
            <div className="flex-1 overflow-y-auto custom-scrollbar">
              {fields.length === 0 ? (
                <div className="p-4 text-center text-sm text-gray-500">
                  No fields yet
                </div>
              ) : (
                fields.map((field, index) => (
                  <DraggableFieldListItem
                    key={field.id}
                    field={field}
                    index={index}
                    moveField={moveField}
                    onFieldClick={onFieldClick}
                    selectedField={selectedField}
                    getFieldIcon={getFieldIcon}
                    COLORS={COLORS}
                  />
                ))
              )}
            </div>
          </div>

          {/* Draggable Divider */}
          <div
            onMouseDown={handleMouseDown}
            className="h-2 bg-gray-100 hover:bg-gray-200 cursor-ns-resize flex items-center justify-center border-y border-gray-200 transition-colors"
            style={{ 
              backgroundColor: isDragging ? '#d1d5db' : undefined,
              userSelect: 'none'
            }}
          >
            <GripHorizontal className="w-4 h-4 text-gray-400" />
          </div>

          {/* Add Fields Section */}
          <div 
            className="flex flex-col"
            style={{ height: `${100 - fieldListHeight}%` }}
          >
            {/* Add Fields Header */}
            <div className="px-4 py-3 border-b border-gray-200 bg-gray-50">
              <h3 className="text-sm font-semibold text-gray-700 uppercase tracking-wide">
                Libraries & Fields
              </h3>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto custom-scrollbar">
              {/* Built-in Field Types */}
              <div className="border-b border-gray-200">
                <button
                  onClick={() => setExpandedBuiltIn(!expandedBuiltIn)}
                  className="w-full flex items-center justify-between p-3 hover:bg-gray-50 transition-colors"
                >
                  <span className="text-sm font-medium text-gray-900">Built-in Fields</span>
                  {expandedBuiltIn ? (
                    <ChevronDown className="w-4 h-4 text-gray-500" />
                  ) : (
                    <ChevronRight className="w-4 h-4 text-gray-500" />
                  )}
                </button>
                
                {expandedBuiltIn && (
                  <div className="pb-2">
                    {getVisibleFieldTypes().map(([key, value]) => (
                      <button
                        key={key}
                        onClick={() => onAddField(key)}
                        className="w-full flex items-center gap-2 px-4 py-2 hover:bg-gray-50 transition-colors group"
                        style={{
                          borderLeft: '3px solid transparent'
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.borderLeftColor = COLORS.primary;
                          e.currentTarget.style.backgroundColor = COLORS.primaryLight;
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.borderLeftColor = 'transparent';
                          e.currentTarget.style.backgroundColor = '';
                        }}
                      >
                        <span className="text-gray-600">{value.icon}</span>
                        <span className="text-sm text-gray-900 flex-1">{value.label}</span>
                        <Plus className="w-4 h-4 text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity" />
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* Library Fields */}
              {libraries.map(library => {
                const libraryFields = getFieldsForLibrary(library.id);
                return (
                  <div key={library.id} className="border-b border-gray-200">
                    <button
                      onClick={() => toggleLibrary(library.id)}
                      className="w-full flex items-center justify-between p-3 hover:bg-gray-50 transition-colors"
                    >
                      <span className="text-sm font-medium text-gray-900">{library.name}</span>
                      {expandedLibraries.has(library.id) ? (
                        <ChevronDown className="w-4 h-4 text-gray-500" />
                      ) : (
                        <ChevronRight className="w-4 h-4 text-gray-500" />
                      )}
                    </button>
                    
                    {expandedLibraries.has(library.id) && (
                      <div className="pb-2">
                        {libraryFields.length === 0 ? (
                          <div className="px-4 py-2 text-xs text-gray-500 italic">
                            No fields in this library
                          </div>
                        ) : (
                          libraryFields.map(field => {
                            const fieldTypeInfo = fieldTypes[field.baseType];
                            return (
                              <button
                                key={field.id}
                                onClick={() => onAddCustomField(field)}
                                className="w-full flex items-center gap-2 px-4 py-2 hover:bg-gray-50 transition-colors group"
                                style={{
                                  borderLeft: '3px solid transparent'
                                }}
                                onMouseEnter={(e) => {
                                  e.currentTarget.style.borderLeftColor = COLORS.primary;
                                  e.currentTarget.style.backgroundColor = COLORS.primaryLight;
                                }}
                                onMouseLeave={(e) => {
                                  e.currentTarget.style.borderLeftColor = 'transparent';
                                  e.currentTarget.style.backgroundColor = '';
                                }}
                              >
                                <span className="text-gray-600">
                                  {fieldTypeInfo?.icon || <span>•</span>}
                                </span>
                                <div className="flex-1 text-left min-w-0">
                                  <div className="text-sm text-gray-900">{field.name}</div>
                                  {field.description && (
                                    <div className="text-xs text-gray-500 truncate">{field.description}</div>
                                  )}
                                </div>
                                <Plus className="w-4 h-4 text-gray-400 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0" />
                              </button>
                            );
                          })
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </>
      ) : (
        /* Collapsed View */
        <div className="flex flex-col h-full">
          {/* Expand Button */}
          <div className="p-3 border-b border-gray-200 flex justify-center">
            <button
              onClick={() => {
                setIsCollapsed(false);
                onCollapsedChange?.(false);
              }}
              className="text-gray-400 hover:text-gray-600 transition-colors"
              title="Expand sidebar"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

          {/* Collapsed Icons */}
          <div className="flex-1 overflow-y-auto custom-scrollbar py-2">
            {/* Field count indicator */}
            <div className="flex justify-center py-2 border-b border-gray-200">
              <div className="relative">
                <svg className="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                </svg>
                {fields.length > 0 && (
                  <div className="absolute -top-1 -right-1 w-3 h-3 rounded-full text-xs flex items-center justify-center" 
                    style={{ backgroundColor: COLORS.primary, fontSize: '8px', color: 'white' }}>
                    {fields.length}
                  </div>
                )}
              </div>
            </div>

            {/* Built-in indicator */}
            <div className="flex justify-center py-2 border-b border-gray-200">
              <svg className="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
              </svg>
            </div>
            
            {/* Library indicators */}
            {libraries.map((library, index) => (
              <div key={library.id} className={`flex justify-center py-2 ${index < libraries.length - 1 ? 'border-b border-gray-200' : ''}`}>
                <svg className="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                </svg>
              </div>
            ))}
          </div>
        </div>
      )}

      <style>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 6px;
        }
        
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #f9fafb;
          border-radius: 3px;
        }
        
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #d1d5db;
          border-radius: 3px;
        }
        
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #9ca3af;
        }
      `}</style>
    </div>
  );
}
