// src/app/features/preview-panel/preview-panel.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TemplateService, FIELD_TYPES } from '../../core/services/template.service';
import { Field } from '../../core/models/types';
import { IconComponent } from '../../shared/components/icon/icon.component';
import { BioPortalSearchModalComponent, BioPortalResult } from '../modals/bioportal-search/bioportal-search.component';

@Component({
  selector: 'app-preview-panel',
  standalone: true,
  imports: [CommonModule, FormsModule, IconComponent, BioPortalSearchModalComponent],
  templateUrl: './preview-panel.component.html',
  styleUrls: ['./preview-panel.component.scss']
})
export class PreviewPanelComponent {
  readonly service = inject(TemplateService);

  readonly selectedTerms = signal<Record<number, any>>({});
  readonly showBioPortalModal = signal(false);
  readonly selectedFieldForSearch = signal<Field | null>(null);

  getFieldPreviewLabel(type: string): string {
    return FIELD_TYPES[type]?.preview || '';
  }

  onInputFocus(el: HTMLElement) {
    el.style.borderColor = this.service.COLORS.primary;
  }

  onInputBlur(el: HTMLElement) {
    el.style.borderColor = '#d1d5db';
  }

  handleOpenBioPortal(field: Field) {
    this.selectedFieldForSearch.set(field);
    this.showBioPortalModal.set(true);
  }

  handleSelectTerm(term: BioPortalResult) {
    const activeField = this.selectedFieldForSearch();
    if (activeField) {
      this.selectedTerms.update(prev => ({
        ...prev,
        [activeField.id]: term
      }));
    }
    this.showBioPortalModal.set(false);
    this.selectedFieldForSearch.set(null);
  }
}

<div class="h-full overflow-y-auto p-8 bg-gray-50 custom-scrollbar relative">
  <!-- Preview Header with Close Button -->
  <div class="absolute top-8 right-8 flex items-center gap-3 z-10">
    <span class="text-sm font-medium text-gray-600">Preview</span>
    <button
      (click)="service.showPreview.set(false)"
      class="w-8 h-8 rounded-full bg-white border border-gray-200 shadow-sm hover:bg-gray-50 transition-colors flex items-center justify-center cursor-pointer"
      title="Close preview"
    >
      <app-icon key="settings" className="w-4 h-4 text-gray-600 rotate-45"></app-icon>
    </button>
  </div>

  <div class="max-w-2xl mx-auto">
    <!-- Form Title and Description -->
    <div class="mb-8">
      <h1 class="text-lg font-medium text-gray-900 mb-2">{{ service.templateName() }}</h1>
      <p *ngIf="service.templateDesc()" class="text-gray-600">{{ service.templateDesc() }}</p>
    </div>

    <!-- Form Fields -->
    <div class="space-y-6">
      <div *ngFor="let field of service.fields()" class="bg-white rounded-lg border border-gray-200 p-5 shadow-sm">
        <!-- Field Label -->
        <label class="block">
          <div class="mb-3">
            <div class="flex items-center gap-2">
              <span class="text-sm font-medium text-gray-900">{{ field.name }}</span>
              <span 
                *ngIf="field.status === 'required'" 
                class="text-xs px-2 py-0.5 rounded-full font-medium bg-red-100 text-red-800"
              >
                Required
              </span>
              <span 
                *ngIf="field.status === 'recommended'" 
                class="text-xs px-2 py-0.5 rounded-full font-medium bg-blue-100 text-blue-800"
              >
                Recommended
              </span>
            </div>
            <p *ngIf="field.helpText" class="text-xs text-gray-500 mt-1">{{ field.helpText }}</p>
          </div>

          <!-- Field Input Based on Type -->
          <!-- Text -->
          <ng-container *ngIf="field.type === 'text'">
            <input 
              type="text" 
              [placeholder]="field.defaultValue || getFieldPreviewLabel(field.type)"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Paragraph -->
          <ng-container *ngIf="field.type === 'paragraph'">
            <textarea 
              rows="4"
              [placeholder]="field.defaultValue || getFieldPreviewLabel(field.type)"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all resize-none"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            ></textarea>
          </ng-container>

          <!-- Multiple Choice -->
          <ng-container *ngIf="field.type === 'multipleChoice'">
            <div class="space-y-2">
              <label *ngFor="let option of field.options; let idx = index" class="flex items-center gap-2 cursor-pointer hover:bg-gray-50 p-2 rounded transition-colors">
                <input 
                  type="radio" 
                  [name]="'field-' + field.id"
                  class="radio-white w-4 h-4"
                />
                <span class="text-sm text-gray-700">{{ option }}</span>
              </label>
            </div>
          </ng-container>

          <!-- Checkboxes -->
          <ng-container *ngIf="field.type === 'checkboxes'">
            <div class="space-y-2">
              <label *ngFor="let option of field.options; let idx = index" class="flex items-center gap-2 cursor-pointer hover:bg-gray-50 p-2 rounded transition-colors">
                <input 
                  type="checkbox"
                  class="checkbox-white w-4 h-4 rounded"
                />
                <span class="text-sm text-gray-700">{{ option }}</span>
              </label>
            </div>
          </ng-container>

          <!-- Date -->
          <ng-container *ngIf="field.type === 'date'">
            <input 
              type="date"
              [value]="field.defaultValue"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Time -->
          <ng-container *ngIf="field.type === 'time'">
            <input 
              type="time"
              [value]="field.defaultValue"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Email -->
          <ng-container *ngIf="field.type === 'email'">
            <input 
              type="email" 
              [placeholder]="field.defaultValue || 'email@example.com'"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Link -->
          <ng-container *ngIf="field.type === 'link'">
            <input 
              type="url"
              [placeholder]="field.defaultValue || 'https://example.com'"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Phone -->
          <ng-container *ngIf="field.type === 'phone'">
            <input 
              type="tel"
              [placeholder]="field.defaultValue || '+1 (555) 000-0000'"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Number -->
          <ng-container *ngIf="field.type === 'number'">
            <input 
              type="number"
              [placeholder]="field.defaultValue || '0'"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Image -->
          <ng-container *ngIf="field.type === 'image'">
            <div class="border-2 border-dashed border-gray-300 rounded-md p-8 text-center hover:border-gray-400 transition-colors cursor-pointer">
              <app-icon key="beaker" className="w-12 h-12 mx-auto mb-3 text-gray-400"></app-icon>
              <p class="text-sm text-gray-600">Click to upload or drag and drop</p>
              <p class="text-xs text-gray-500 mt-1">PNG, JPG, GIF up to 10MB</p>
            </div>
          </ng-container>

          <!-- ORCID -->
          <ng-container *ngIf="field.type === 'orcid'">
            <input 
              type="text"
              [placeholder]="field.defaultValue || '0000-0000-0000-0000'"
              class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all font-mono"
              [style.--tw-ring-color]="service.COLORS.primary"
              (focus)="onInputFocus($any($event.target))"
              (blur)="onInputBlur($any($event.target))"
            />
          </ng-container>

          <!-- Controlled Terms -->
          <ng-container *ngIf="field.type === 'controlledTerms'">
            <div>
              <button
                type="button"
                (click)="handleOpenBioPortal(field)"
                class="w-full px-3 py-2 border-2 border-dashed border-gray-300 rounded-md hover:border-gray-400 transition-colors text-left flex items-center gap-2 group cursor-pointer"
              >
                <div *ngIf="selectedTerms()[field.id]; else noTerm" class="flex-1">
                  <div class="text-sm font-medium text-gray-900">
                    {{ selectedTerms()[field.id].prefLabel }}
                  </div>
                  <div *ngIf="selectedTerms()[field.id].ontologyAcronym" class="text-xs text-gray-500 mt-0.5">
                    {{ selectedTerms()[field.id].ontologyAcronym }}
                  </div>
                </div>
                <ng-template #noTerm>
                  <div class="flex items-center gap-2 flex-1 text-gray-500">
                    <app-icon key="settings" className="w-5 h-5"></app-icon>
                    <span class="text-sm font-normal">Search BioPortal...</span>
                  </div>
                </ng-template>
                <span class="text-sm text-gray-400 group-hover:text-gray-600 transition-colors">▶</span>
              </button>
            </div>
          </ng-container>
        </label>
      </div>
    </div>
  </div>
</div>

<!-- BioPortal Search Modal Wrapper -->
<app-bioportal-search-modal
  [isOpen]="showBioPortalModal()"
  [fieldName]="selectedFieldForSearch()?.name || ''"
  [config]="selectedFieldForSearch()?.controlledTermConfig"
  (close)="showBioPortalModal.set(false); selectedFieldForSearch.set(null)"
  (select)="handleSelectTerm($event)"
></app-bioportal-search-modal>

// react-src-backup/src/app/PreviewPanel.tsx
import { useState } from 'react';
import { BioPortalSearchModal } from './components/BioPortalSearchModal';

interface Field {
  id: number;
  type: string;
  name: string;
  status: string;
  options: string[];
  defaultValue: string;
  allowMultiple: boolean;
  helpText?: string;
  controlledTermConfig?: {
    sourceType: 'ontology-term' | 'ontology' | 'value-set' | 'ontology-branch';
    sourceId?: string;
    sourceName?: string;
    ontologyId?: string;
    ontologyName?: string;
    branchRootId?: string;
    branchRootName?: string;
    restrictedOntologies?: string[];
    searchDepth?: number;
  };
}

interface PreviewPanelProps {
  fields: Field[];
  templateName: string;
  templateDesc: string;
  onClose: () => void;
  apiKey: string;
  FIELD_TYPES: Record<string, { icon: JSX.Element; label: string; preview: string }>;
  COLORS: {
    primary: string;
    primaryHover: string;
    primaryLight: string;
    border: string;
  };
}

export function PreviewPanel({ fields, templateName, templateDesc, onClose, apiKey, FIELD_TYPES, COLORS }: PreviewPanelProps) {
  const [showBioPortalModal, setShowBioPortalModal] = useState(false);
  const [selectedFieldForSearch, setSelectedFieldForSearch] = useState<Field | null>(null);
  const [selectedTerms, setSelectedTerms] = useState<Record<number, any>>({});

  const handleOpenBioPortal = (field: Field) => {
    setSelectedFieldForSearch(field);
    setShowBioPortalModal(true);
  };

  const handleSelectTerm = (term: any) => {
    if (selectedFieldForSearch) {
      setSelectedTerms({
        ...selectedTerms,
        [selectedFieldForSearch.id]: term
      });
    }
    setShowBioPortalModal(false);
    setSelectedFieldForSearch(null);
  };

  return (
    <div className="h-full overflow-y-auto p-8 bg-gray-50 custom-scrollbar relative">
      {/* Preview Header with Close Button */}
      <div className="absolute top-8 right-8 flex items-center gap-3 z-10">
        <span className="text-sm font-medium text-gray-600">Preview</span>
        <button
          onClick={onClose}
          className="w-8 h-8 rounded-full bg-white border border-gray-200 shadow-sm hover:bg-gray-50 transition-colors flex items-center justify-center"
          title="Close preview"
        >
          <svg className="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      
      <div className="max-w-2xl mx-auto">
        {/* Form Title and Description */}
        <div className="mb-8">
          <h1 className="text-lg font-medium text-gray-900 mb-2">{templateName}</h1>
          {templateDesc && <p className="text-gray-600">{templateDesc}</p>}
        </div>

        {/* Form Fields */}
        <div className="space-y-6">
          {fields.map((field) => (
            <div key={field.id} className="bg-white rounded-lg border border-gray-200 p-5 shadow-sm">
              {/* Field Label */}
              <label className="block">
                <div className="mb-3">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-gray-900">{field.name}</span>
                    {field.status === 'required' && (
                      <span className="text-xs px-2 py-0.5 rounded-full font-medium" style={{ backgroundColor: '#FEE2E2', color: '#991B1B' }}>
                        Required
                      </span>
                    )}
                    {field.status === 'recommended' && (
                      <span className="text-xs px-2 py-0.5 rounded-full font-medium" style={{ backgroundColor: '#DBEAFE', color: '#1E40AF' }}>
                        Recommended
                      </span>
                    )}
                  </div>
                  {field.helpText && (
                    <p className="text-xs text-gray-500 mt-1">{field.helpText}</p>
                  )}
                </div>

                {/* Field Input Based on Type */}
                {field.type === 'text' && (
                  <input 
                    type="text" 
                    placeholder={field.defaultValue || FIELD_TYPES[field.type].preview}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'paragraph' && (
                  <textarea 
                    rows={4}
                    placeholder={field.defaultValue || FIELD_TYPES[field.type].preview}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all resize-none"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'multipleChoice' && (
                  <div className="space-y-2">
                    {field.options.map((option, idx) => (
                      <label key={idx} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50 p-2 rounded transition-colors">
                        <input 
                          type="radio" 
                          name={`field-${field.id}`}
                          className="radio-white w-4 h-4"
                        />
                        <span className="text-sm text-gray-700">{option}</span>
                      </label>
                    ))}
                  </div>
                )}

                {field.type === 'checkboxes' && (
                  <div className="space-y-2">
                    {field.options.map((option, idx) => (
                      <label key={idx} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50 p-2 rounded transition-colors">
                        <input 
                          type="checkbox"
                          className="checkbox-white w-4 h-4 rounded"
                        />
                        <span className="text-sm text-gray-700">{option}</span>
                      </label>
                    ))}
                  </div>
                )}

                {field.type === 'date' && (
                  <input 
                    type="date"
                    defaultValue={field.defaultValue}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'time' && (
                  <input 
                    type="time"
                    defaultValue={field.defaultValue}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'email' && (
                  <input 
                    type="email"
                    placeholder={field.defaultValue || 'email@example.com'}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'link' && (
                  <input 
                    type="url"
                    placeholder={field.defaultValue || 'https://example.com'}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'phone' && (
                  <input 
                    type="tel"
                    placeholder={field.defaultValue || '+1 (555) 000-0000'}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'number' && (
                  <input 
                    type="number"
                    placeholder={field.defaultValue || '0'}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'image' && (
                  <div className="border-2 border-dashed border-gray-300 rounded-md p-8 text-center hover:border-gray-400 transition-colors cursor-pointer">
                    <svg className="w-12 h-12 mx-auto mb-3 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                    </svg>
                    <p className="text-sm text-gray-600">Click to upload or drag and drop</p>
                    <p className="text-xs text-gray-500 mt-1">PNG, JPG, GIF up to 10MB</p>
                  </div>
                )}

                {field.type === 'orcid' && (
                  <input 
                    type="text"
                    placeholder={field.defaultValue || '0000-0000-0000-0000'}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 transition-all font-mono"
                    style={{ 
                      '--tw-ring-color': COLORS.primary,
                    } as React.CSSProperties}
                    onFocus={(e) => e.target.style.borderColor = COLORS.primary}
                    onBlur={(e) => e.target.style.borderColor = '#d1d5db'}
                  />
                )}

                {field.type === 'controlledTerms' && (
                  <div>
                    <button
                      onClick={() => handleOpenBioPortal(field)}
                      className="w-full px-3 py-2 border-2 border-dashed border-gray-300 rounded-md hover:border-gray-400 transition-colors text-left flex items-center gap-2 group"
                    >
                      {selectedTerms[field.id] ? (
                        <div className="flex-1">
                          <div className="text-sm font-medium text-gray-900">
                            {selectedTerms[field.id].prefLabel}
                          </div>
                          {selectedTerms[field.id].ontologyAcronym && (
                            <div className="text-xs text-gray-500 mt-0.5">
                              {selectedTerms[field.id].ontologyAcronym}
                            </div>
                          )}
                        </div>
                      ) : (
                        <div className="flex items-center gap-2 flex-1 text-gray-500">
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                          </svg>
                          <span className="text-sm">Search BioPortal...</span>
                        </div>
                      )}
                      <svg 
                        className="w-4 h-4 text-gray-400 group-hover:text-gray-600 transition-colors flex-shrink-0" 
                        fill="none" 
                        stroke="currentColor" 
                        viewBox="0 0 24 24"
                      >
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </button>
                    {selectedTerms[field.id]?.definition?.[0] && (
                      <p className="text-xs text-gray-600 mt-2 pl-3 border-l-2 border-teal-500">
                        {selectedTerms[field.id].definition[0]}
                      </p>
                    )}
                  </div>
                )}

                {field.allowMultiple && (
                  <p className="text-xs text-gray-500 mt-2 italic">Multiple values allowed</p>
                )}
              </label>
            </div>
          ))}
        </div>
      </div>

      {/* BioPortal Search Modal */}
      {showBioPortalModal && selectedFieldForSearch && (
        <BioPortalSearchModal
          isOpen={showBioPortalModal}
          onClose={() => {
            setShowBioPortalModal(false);
            setSelectedFieldForSearch(null);
          }}
          onSelect={handleSelectTerm}
          fieldName={selectedFieldForSearch.name}
          config={selectedFieldForSearch.controlledTermConfig}
          apiKey={apiKey}
          COLORS={COLORS}
        />
      )}
    </div>
  );
}
